# Generated by Django 2.1.2 on 2018-10-26 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readingapp', '0002_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='details',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
